//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleJetBA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleJetBA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configured.
        /// </summary>
        public static string _0Configured {
            get {
                return ResourceManager.GetString("_0Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} database connection.
        /// </summary>
        public static string _0DatabaseConnection {
            get {
                return ResourceManager.GetString("_0DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} install folder.
        /// </summary>
        public static string _0InstallFolder {
            get {
                return ResourceManager.GetString("_0InstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a legal folder name.
        /// </summary>
        public static string _0IsNotALegalFolderName {
            get {
                return ResourceManager.GetString("_0IsNotALegalFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready for use.
        /// </summary>
        public static string _0IsReadyForUse {
            get {
                return ResourceManager.GetString("_0IsReadyForUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service account.
        /// </summary>
        public static string _0ServiceAccount {
            get {
                return ResourceManager.GetString("_0ServiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching {0}.
        /// </summary>
        public static string Caching0 {
            get {
                return ResourceManager.GetString("Caching0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will not take fffect until you reboot the system.
        /// </summary>
        public static string ChangesWillNotTakeEffectUntilReboot {
            get {
                return ResourceManager.GetString("ChangesWillNotTakeEffectUntilReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Repair&apos; to repair {0} or &apos;Uninstall&apos; to remove it.
        /// </summary>
        public static string ClickRepairToRepair0OrUninstallToRemoveIt {
            get {
                return ResourceManager.GetString("ClickRepairToRepair0OrUninstallToRemoveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection.
        /// </summary>
        public static string DatabaseConnection {
            get {
                return ResourceManager.GetString("DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Server.
        /// </summary>
        public static string DbServer {
            get {
                return ResourceManager.GetString("DbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}.
        /// </summary>
        public static string Executing0 {
            get {
                return ResourceManager.GetString("Executing0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed configuring {0}.
        /// </summary>
        public static string FailedConfiguring0 {
            get {
                return ResourceManager.GetString("FailedConfiguring0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed connecting to DB server
        ///{0}.
        /// </summary>
        public static string FailedConnectingToDbServer0 {
            get {
                return ResourceManager.GetString("FailedConnectingToDbServer0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed installing {0}.
        /// </summary>
        public static string FailedInstalling0 {
            get {
                return ResourceManager.GetString("FailedInstalling0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed removing {0}.
        /// </summary>
        public static string FailedRemoving0 {
            get {
                return ResourceManager.GetString("FailedRemoving0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Ready ....
        /// </summary>
        public static string GettingReady {
            get {
                return ResourceManager.GetString("GettingReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /install | /repair | /uninstall | /layout &quot;C:\Users\Me\Desktop\Extract&quot; - installs, repairs, uninstalls or downloads a complete local copy of the bundle in directory. Install is the default.
        ///
        ////passive - Displays minimal UI with no prompts.
        ////quiet - Displays no UI and no prompts.
        ///By default UI and all prompts are displayed.
        ///
        ////norestart - Suppress any attempts to restart. By default UI will prompt before restart.
        ////log log.txt - Logs to a specific file. By default a log file is created in %TEMP%.
        ////lang [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpPageText {
            get {
                return ResourceManager.GetString("HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation folder.
        /// </summary>
        public static string InstallationFolder {
            get {
                return ResourceManager.GetString("InstallationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Folder.
        /// </summary>
        public static string InstallFolder {
            get {
                return ResourceManager.GetString("InstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string IS_RIGHT_TO_LEFT {
            get {
                return ResourceManager.GetString("IS_RIGHT_TO_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open failure log.
        /// </summary>
        public static string OpenFailureLog {
            get {
                return ResourceManager.GetString("OpenFailureLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection.
        /// </summary>
        public static string PageTitle_Database {
            get {
                return ResourceManager.GetString("PageTitle_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string PageTitle_Finish {
            get {
                return ResourceManager.GetString("PageTitle_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        public static string PageTitle_InstallLocation {
            get {
                return ResourceManager.GetString("PageTitle_InstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select features.
        /// </summary>
        public static string PageTitle_PageSelection {
            get {
                return ResourceManager.GetString("PageTitle_PageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install progress.
        /// </summary>
        public static string PageTitle_Progress {
            get {
                return ResourceManager.GetString("PageTitle_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string PageTitle_Repair {
            get {
                return ResourceManager.GetString("PageTitle_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service account.
        /// </summary>
        public static string PageTitle_Service {
            get {
                return ResourceManager.GetString("PageTitle_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install.
        /// </summary>
        public static string PageTitle_Summary {
            get {
                return ResourceManager.GetString("PageTitle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide user name for SQL authentication.
        /// </summary>
        public static string PleaseProvideSqlUserName {
            get {
                return ResourceManager.GetString("PleaseProvideSqlUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we&apos;re preparing the system.
        /// </summary>
        public static string PleasWaitWhileExecuting {
            get {
                return ResourceManager.GetString("PleasWaitWhileExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review parameters and click &apos;Install&apos; when ready.
        /// </summary>
        public static string ReadyToInstall {
            get {
                return ResourceManager.GetString("ReadyToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pages for the Installation Wizard.
        /// </summary>
        public static string SelectInstallationPages {
            get {
                return ResourceManager.GetString("SelectInstallationPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service account.
        /// </summary>
        public static string ServiceAccount {
            get {
                return ResourceManager.GetString("ServiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string SqlAuthentication {
            get {
                return ResourceManager.GetString("SqlAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for having used {0}.
        /// </summary>
        public static string ThankYouForHavingUsed0 {
            get {
                return ResourceManager.GetString("ThankYouForHavingUsed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowsAuthentication {
            get {
                return ResourceManager.GetString("WindowsAuthentication", resourceCulture);
            }
        }
    }
}
