//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleJetBA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleJetBA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configured.
        /// </summary>
        public static string _0Configured {
            get {
                return ResourceManager.GetString("_0Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} database connection.
        /// </summary>
        public static string _0DatabaseConnection {
            get {
                return ResourceManager.GetString("_0DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} install folder.
        /// </summary>
        public static string _0InstallFolder {
            get {
                return ResourceManager.GetString("_0InstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a legal folder name.
        /// </summary>
        public static string _0IsNotALegalFolderName {
            get {
                return ResourceManager.GetString("_0IsNotALegalFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is ready for use.
        /// </summary>
        public static string _0IsReadyForUse {
            get {
                return ResourceManager.GetString("_0IsReadyForUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} service account.
        /// </summary>
        public static string _0ServiceAccount {
            get {
                return ResourceManager.GetString("_0ServiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching {0}.
        /// </summary>
        public static string Caching0 {
            get {
                return ResourceManager.GetString("Caching0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelCaption {
            get {
                return ResourceManager.GetString("CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CancelNo {
            get {
                return ResourceManager.GetString("CancelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        public static string CancelPrompt {
            get {
                return ResourceManager.GetString("CancelPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CancelYes {
            get {
                return ResourceManager.GetString("CancelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will not take fffect until you reboot the system.
        /// </summary>
        public static string ChangesWillNotTakeEffectUntilReboot {
            get {
                return ResourceManager.GetString("ChangesWillNotTakeEffectUntilReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Repair&apos; to repair {0} or &apos;Uninstall&apos; to remove it.
        /// </summary>
        public static string ClickRepairToRepair0OrUninstallToRemoveIt {
            get {
                return ResourceManager.GetString("ClickRepairToRepair0OrUninstallToRemoveIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection.
        /// </summary>
        public static string DatabaseConnection {
            get {
                return ResourceManager.GetString("DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Server.
        /// </summary>
        public static string DbServer {
            get {
                return ResourceManager.GetString("DbServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation/removal of a previous program was not completed. You will need to restart your computer to complete that installation.
        ///
        ///After restarting your computer, run Setup again to complete the installation of {0}..
        /// </summary>
        public static string ERROR_FAIL_NOACTION_REBOOT_0 {
            get {
                return ResourceManager.GetString("ERROR_FAIL_NOACTION_REBOOT_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing {0}.
        /// </summary>
        public static string Executing0 {
            get {
                return ResourceManager.GetString("Executing0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed configuring {0}.
        /// </summary>
        public static string FailedConfiguring0 {
            get {
                return ResourceManager.GetString("FailedConfiguring0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed connecting to DB server
        ///{0}.
        /// </summary>
        public static string FailedConnectingToDbServer0 {
            get {
                return ResourceManager.GetString("FailedConnectingToDbServer0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed installing {0}.
        /// </summary>
        public static string FailedInstalling0 {
            get {
                return ResourceManager.GetString("FailedInstalling0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed removing {0}.
        /// </summary>
        public static string FailedRemoving0 {
            get {
                return ResourceManager.GetString("FailedRemoving0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files in Use.
        /// </summary>
        public static string FilesInUse {
            get {
                return ResourceManager.GetString("FilesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following applications are using files that need to be updated by this setup. You can let Setup Wizard close them and attempt to restart them or reboot the machine later..
        /// </summary>
        public static string FilesInUseText {
            get {
                return ResourceManager.GetString("FilesInUseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Ready ....
        /// </summary>
        public static string GettingReady {
            get {
                return ResourceManager.GetString("GettingReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /install | /repair | /uninstall | /layout &quot;C:\Users\Me\Desktop\Extract&quot; - installs, repairs, uninstalls or downloads a complete local copy of the bundle in directory. Install is the default.
        ///
        ////passive - Displays minimal UI with no prompts.
        ////quiet - Displays no UI and no prompts.
        ///By default UI and all prompts are displayed.
        ///
        ////norestart - Suppress any attempts to restart. By default UI will prompt before restart.
        ////log log.txt - Logs to a specific file. By default a log file is created in %TEMP%.
        ////lang [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpPageText {
            get {
                return ResourceManager.GetString("HelpPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation folder.
        /// </summary>
        public static string InstallationFolder {
            get {
                return ResourceManager.GetString("InstallationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while {0} is being installed..
        /// </summary>
        public static string InstallationIsRunningFormat {
            get {
                return ResourceManager.GetString("InstallationIsRunningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Folder.
        /// </summary>
        public static string InstallFolder {
            get {
                return ResourceManager.GetString("InstallFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine has restarted. Do you wish to proceed with the operation started before the reboot?.
        /// </summary>
        public static string InterruptedRebootPrompt {
            get {
                return ResourceManager.GetString("InterruptedRebootPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string IS_RIGHT_TO_LEFT {
            get {
                return ResourceManager.GetString("IS_RIGHT_TO_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open failure log.
        /// </summary>
        public static string OpenFailureLog {
            get {
                return ResourceManager.GetString("OpenFailureLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Aborted.
        /// </summary>
        public static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string PackageRetryPromptCaption {
            get {
                return ResourceManager.GetString("PackageRetryPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection.
        /// </summary>
        public static string PageTitle_Database {
            get {
                return ResourceManager.GetString("PageTitle_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string PageTitle_Finish {
            get {
                return ResourceManager.GetString("PageTitle_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        public static string PageTitle_InstallLocation {
            get {
                return ResourceManager.GetString("PageTitle_InstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select features.
        /// </summary>
        public static string PageTitle_PageSelection {
            get {
                return ResourceManager.GetString("PageTitle_PageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install progress.
        /// </summary>
        public static string PageTitle_Progress {
            get {
                return ResourceManager.GetString("PageTitle_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string PageTitle_Repair {
            get {
                return ResourceManager.GetString("PageTitle_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service account.
        /// </summary>
        public static string PageTitle_Service {
            get {
                return ResourceManager.GetString("PageTitle_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install.
        /// </summary>
        public static string PageTitle_Summary {
            get {
                return ResourceManager.GetString("PageTitle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide user name for SQL authentication.
        /// </summary>
        public static string PleaseProvideSqlUserName {
            get {
                return ResourceManager.GetString("PleaseProvideSqlUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we&apos;re preparing the system.
        /// </summary>
        public static string PleasWaitWhileExecuting {
            get {
                return ResourceManager.GetString("PleasWaitWhileExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing older versions of this application....
        /// </summary>
        public static string PreviousVersion {
            get {
                return ResourceManager.GetString("PreviousVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review parameters and click &apos;Install&apos; when ready.
        /// </summary>
        public static string ReadyToInstall {
            get {
                return ResourceManager.GetString("ReadyToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        public static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pages for the Installation Wizard.
        /// </summary>
        public static string SelectInstallationPages {
            get {
                return ResourceManager.GetString("SelectInstallationPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service account.
        /// </summary>
        public static string ServiceAccount {
            get {
                return ResourceManager.GetString("ServiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute file:
        ///{0}.
        /// </summary>
        public static string ShellExecuteFailedTextFormat {
            get {
                return ResourceManager.GetString("ShellExecuteFailedTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL.
        /// </summary>
        public static string SqlAuthentication {
            get {
                return ResourceManager.GetString("SqlAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for having used {0}.
        /// </summary>
        public static string ThankYouForHavingUsed0 {
            get {
                return ResourceManager.GetString("ThankYouForHavingUsed0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ValidationPromptCancel {
            get {
                return ResourceManager.GetString("ValidationPromptCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string ValidationPromptContinue {
            get {
                return ResourceManager.GetString("ValidationPromptContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ValidationPromptOk {
            get {
                return ResourceManager.GetString("ValidationPromptOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to reboot the machine now.
        ///{0} will continue after you login again.
        /// </summary>
        public static string WeNeedToRebootNow_0WillContinueAfterYouLoginAgain {
            get {
                return ResourceManager.GetString("WeNeedToRebootNow_0WillContinueAfterYouLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string WindowsAuthentication {
            get {
                return ResourceManager.GetString("WindowsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
