name: JetBA-Showcase
on:
  workflow_dispatch:
    inputs:
      jetba_version:
        description: 'JetBA5 Version'
        required: true
        default: '8.1.0.145'
        type: string
      wix_version:
        description: 'WixToolset v4 Version'
        required: true
        default: '5.0.0'
        type: string
      psw_wix_version:
        description: 'PanelSwWix4 Version'
        required: true
        default: '6.0.0-psw-wix.0276-14'
        type: string
      create_tag:
        description: 'Create tag?'
        required: true
        default: false
        type: boolean

jobs:
  JetBA-Showcase-Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: |
          msbuild dirs.proj -restore -p:Configuration=Release -p:FullVersion=${{ github.event.inputs.jetba_version }} -p:WixToolsetVersion=${{ github.event.inputs.wix_version }} -p:JetBaVersion=${{ github.event.inputs.jetba_version }}

      - name: Build for psw-wix
        run: |
          $buildPswWixFolder = [System.IO.Path]::Combine('${{ github.workspace }}', 'build-psw')
          msbuild dirs.proj -t:WixtoolsetToPanelSwWix4 -p:Configuration=Release -p:JetBaVersion=${{ github.event.inputs.jetba_version }} -p:"BaseBuildFolder=$buildPswWixFolder\"
          msbuild dirs.proj -restore -p:Configuration=Release -p:FullVersion=${{ github.event.inputs.jetba_version }} -p:PanelSwWix4Version=${{ github.event.inputs.psw_wix_version }} -p:"BaseBuildFolder=$buildPswWixFolder\"

      - uses: actions/upload-artifact@v2
        with:
          name: JetBA_Showcase.exe
          path: build\bin\Release\Bootstrapper\JetBA_Showcase.exe

      - uses: actions/upload-artifact@v2
        with:
          name: JetBA_Showcase-psw-wix.exe
          path: build-psw\bin\Release\Bootstrapper\JetBA_Showcase.exe

      - name: Tag
        if: ${{ github.event.inputs.create_tag == 'true' }}
        run: |
          git tag wix4-v${{ github.event.inputs.jetba_version }}-build.${{ github.run_number }}
          git push --tags
