name: JetBA
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  JetBA-Showcase-Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.0.2
      - run: nuget restore

      - name: Build for default WiX
        run: msbuild JetBA.sln -m -p:Configuration=Release

      - uses: actions/upload-artifact@v2
        with:
          name: JetBA_Showcase.exe
          path: build\bin\Release\Bootstrapper\JetBA_Showcase.exe